In [1]:
import pandas as pd
import numpy as np

In [2]:
# read parquet file
df = pd.read_parquet('data/brasil_dengue_clima_final.parquet')
df

,ID_MUNICIP,NOMBRE_MUNICIPIO,SG_UF,NU_ANO,MES,DT_NOTIFIC,DT_SIN_PRI,CS_SEXO,NU_IDADE,CLASIFICACION,EVOLUCION,HOSPITALIZADO,LATITUD,LONGITUD,TempMin,TempMax,Precipitacion
0,310670,Betim,31,2007,3,2007-03-12,2007-03-11,M,4030,5.0,NaN,NaN,-19.96680,-44.2008,17.0,30.0,74.800003
1,310670,Betim,31,2007,3,2007-03-06,2007-03-05,M,4032,5.0,NaN,NaN,-19.96680,-44.2008,17.0,30.0,74.800003
2,310670,Betim,31,2007,3,2007-03-15,2007-03-12,F,4030,1.0,1.0,NaN,-19.96680,-44.2008,17.0,30.0,74.800003
3,310670,Betim,31,2007,3,2007-03-15,2007-03-13,F,4023,1.0,1.0,NaN,-19.96680,-44.2008,17.0,30.0,74.800003
4,310670,Betim,31,2007,3,2007-03-15,2007-03-12,M,4032,1.0,1.0,NaN,-19.96680,-44.2008,17.0,30.0,74.800003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30133094,220830,Piracuruca,22,2007,6,2007-06-23,2007-06-21,M,4023,5.0,NaN,NaN,-3.93335,-41.7088,21.0,32.0,36.900002
30133095,220770,Parnaíba,22,2007,5,2007-05-29,2007-05-19,F,4024,1.0,1.0,NaN,-2.90585,-41.7754,24.0,32.0,120.099998
30133096,220770,Parnaíba,22,2007,5,2007-05-29,2007-05-24,F,4023,1.0,1.0,NaN,-2.90585,-41.7754,24.0,32.0,120.099998
30133097,220830,Piracuruca,22,2007,6,2007-06-26,2007-06-24,F,4045,1.0,NaN,NaN,-3.93335,-41.7088,21.0,32.0,36.900002
30133098,220830,Piracuruca,22,2007,6,2007-06-25,2007-06-22,F,4011,1.0,1.0,NaN,-3.93335,-41.7088,21.0,32.0,36.900002

In [5]:
# get the number of records per 'NOMBRE_MUNICIPIO','NU_ANO','MES' as dictionary
records_per_municipality = df.groupby(['NOMBRE_MUNICIPIO', 'NU_ANO', 'MES']).size().to_dict()
records_per_municipality

{('Abadia de Goiás', 2007, 1): 1,
 ('Abadia de Goiás', 2007, 2): 1,
 ('Abadia de Goiás', 2007, 3): 3,
 ('Abadia de Goiás', 2007, 4): 6,
 ('Abadia de Goiás', 2007, 6): 3,
 ('Abadia de Goiás', 2007, 11): 3,
 ('Abadia de Goiás', 2007, 12): 3,
 ('Abadia de Goiás', 2008, 1): 2,
 ('Abadia de Goiás', 2008, 2): 1,
 ('Abadia de Goiás', 2008, 3): 4,
 ('Abadia de Goiás', 2008, 4): 57,
 ('Abadia de Goiás', 2008, 5): 11,
 ('Abadia de Goiás', 2008, 6): 5,
 ('Abadia de Goiás', 2008, 7): 2,
 ('Abadia de Goiás', 2008, 8): 2,
 ('Abadia de Goiás', 2008, 11): 1,
 ('Abadia de Goiás', 2009, 1): 1,
 ('Abadia de Goiás', 2009, 2): 3,
 ('Abadia de Goiás', 2009, 3): 7,
 ('Abadia de Goiás', 2009, 4): 7,
 ('Abadia de Goiás', 2009, 5): 1,
 ('Abadia de Goiás', 2009, 8): 1,
 ('Abadia de Goiás', 2009, 10): 1,
 ('Abadia de Goiás', 2009, 12): 7,
 ('Abadia de Goiás', 2010, 1): 16,
 ('Abadia de Goiás', 2010, 2): 22,
 ('Abadia de Goiás', 2010, 3): 10,
 ('Abadia de Goiás', 2010, 4): 1,
 ('Abadia de Goiás', 2010, 5): 5,
 ('Abadia de Goiás', 2010, 6): 8,
 ('Abadia de Goiás', 2010, 7): 24,
 ('Abadia de Goiás', 2010, 8): 4,
 ('Abadia de Goiás', 2010, 10): 6,
 ('Abadia de Goiás', 2010, 11): 2,
 ('Abadia de Goiás', 2010, 12): 2,
 ('Abadia de Goiás', 2011, 1): 10,
 ('Abadia de Goiás', 2011, 2): 18,
 ('Abadia de Goiás', 2011, 3): 11,
 ('Abadia de Goiás', 2011, 4): 4,
 ('Abadia de Goiás', 2011, 5): 7,
 ('Abadia de Goiás', 2011, 6): 7,
 ('Abadia de Goiás', 2011, 7): 4,
 ('Abadia de Goiás', 2011, 8): 4,
 ('Abadia de Goiás', 2011, 10): 9,
 ('Abadia de Goiás', 2011, 11): 2,
 ('Abadia de Goiás', 2011, 12): 3,
 ('Abadia de Goiás', 2012, 1): 2,
 ('Abadia de Goiás', 2012, 2): 1,
 ('Abadia de Goiás', 2012, 3): 5,
 ('Abadia de Goiás', 2012, 4): 3,
 ('Abadia de Goiás', 2012, 6): 2,
 ('Abadia de Goiás', 2012, 7): 2,
 ('Abadia de Goiás', 2012, 8): 1,
 ('Abadia de Goiás', 2012, 9): 1,
 ('Abadia de Goiás', 2012, 12): 1,
 ('Abadia de Goiás', 2013, 1): 13,
 ('Abadia de Goiás', 2013, 2): 21,
 ('Abadia de Goiás', 2013, 3): 45,
 ('Abadia de Goiás', 2013, 4): 39,
 ('Abadia de Goiás', 2013, 5): 16,
 ('Abadia de Goiás', 2013, 6): 10,
 ('Abadia de Goiás', 2013, 7): 5,
 ('Abadia de Goiás', 2014, 1): 2,
 ('Abadia de Goiás', 2014, 2): 4,
 ('Abadia de Goiás', 2014, 3): 6,
 ('Abadia de Goiás', 2014, 4): 14,
 ('Abadia de Goiás', 2014, 5): 18,
 ('Abadia de Goiás', 2014, 6): 6,
 ('Abadia de Goiás', 2014, 7): 4,
 ('Abadia de Goiás', 2014, 8): 2,
 ('Abadia de Goiás', 2014, 9): 6,
 ('Abadia de Goiás', 2014, 10): 2,
 ('Abadia de Goiás', 2014, 11): 2,
 ('Abadia de Goiás', 2015, 1): 5,
 ('Abadia de Goiás', 2015, 2): 19,
 ('Abadia de Goiás', 2015, 3): 32,
 ('Abadia de Goiás', 2015, 4): 36,
 ('Abadia de Goiás', 2015, 5): 37,
 ('Abadia de Goiás', 2015, 6): 8,
 ('Abadia de Goiás', 2015, 7): 1,
 ('Abadia de Goiás', 2015, 9): 2,
 ('Abadia de Goiás', 2015, 12): 5,
 ('Abadia de Goiás', 2016, 1): 34,
 ('Abadia de Goiás', 2016, 2): 26,
 ('Abadia de Goiás', 2016, 3): 9,
 ('Abadia de Goiás', 2016, 4): 4,
 ('Abadia de Goiás', 2016, 5): 4,
 ('Abadia de Goiás', 2016, 6): 3,
 ('Abadia de Goiás', 2016, 7): 2,
 ('Abadia de Goiás', 2016, 8): 2,
 ('Abadia de Goiás', 2016, 9): 1,
 ('Abadia de Goiás', 2016, 10): 1,
 ('Abadia de Goiás', 2017, 1): 1,
 ('Abadia de Goiás', 2017, 2): 7,
 ('Abadia de Goiás', 2017, 3): 14,
 ('Abadia de Goiás', 2017, 4): 7,
 ('Abadia de Goiás', 2017, 5): 8,
 ('Abadia de Goiás', 2017, 6): 5,
 ('Abadia de Goiás', 2017, 7): 1,
 ('Abadia de Goiás', 2017, 8): 10,
 ('Abadia de Goiás', 2017, 9): 2,
 ('Abadia de Goiás', 2017, 11): 1,
 ('Abadia de Goiás', 2018, 1): 7,
 ('Abadia de Goiás', 2018, 2): 11,
 ('Abadia de Goiás', 2018, 3): 17,
 ('Abadia de Goiás', 2018, 4): 15,
 ('Abadia de Goiás', 2018, 5): 4,
 ('Abadia de Goiás', 2018, 6): 3,
 ('Abadia de Goiás', 2018, 7): 3,
 ('Abadia de Goiás', 2018, 8): 3,
 ('Abadia de Goiás', 2018, 9): 2,
 ('Abadia de Goiás', 2018, 10): 11,
 ('Abadia de Goiás', 2018, 11): 18,
 ('Abadia de Goiás', 2018, 12): 14,
 ('Abadia de Goiás', 2019, 1): 20,
 ('Abadia de Goiás', 2019, 2): 33,
 ('Abadia de Goiás', 2019, 3): 24,
 ('Abadia de Goiás', 2019, 4): 18,
 ('Abadia de Goiás', 2019, 5): 9,
 ('Abadia de Goiás', 2019, 8): 2,
 ('Abadia de Goiás', 2019, 11): 5,
 ('Abadia de Goiás', 2019, 12): 3,
 ('Abadia de Goiás', 2020, 1): 2,
 ('Abadia de Goiás', 2020, 2): 3,
 ('Abadia de Goiás', 2020, 3): 2,
 ('Abadia de Goiás', 2020, 4): 1,
 ('Abadia de Goiás', 2020, 5): 2,
 ('Abadia de Goiás', 2020, 6): 3,
 ('Abadia de Goiás', 2020, 8): 3,
 ('Abadia de Goiás', 2020, 9): 4,
 ('Abadia de Goiás', 2020, 10): 1,
 ('Abadia de Goiás', 2020, 11): 2,
 ('Abadia de Goiás', 2020, 12): 1,
 ('Abadia de Goiás', 2021, 3): 1,
 ('Abadia de Goiás', 2021, 4): 1,
 ('Abadia de Goiás', 2021, 5): 1,
 ('Abadia de Goiás', 2021, 8): 1,
 ('Abadia de Goiás', 2021, 10): 7,
 ('Abadia de Goiás', 2021, 11): 21,
 ('Abadia de Goiás', 2021, 12): 159,
 ('Abadia de Goiás', 2022, 1): 13,
 ('Abadia de Goiás', 2022, 2): 30,
 ('Abadia de Goiás', 2022, 3): 51,
 ('Abadia de Goiás', 2022, 4): 37,
 ('Abadia de Goiás', 2022, 5): 37,
 ('Abadia de Goiás', 2022, 6): 11,
 ('Abadia de Goiás', 2022, 7): 4,
 ('Abadia de Goiás', 2022, 8): 1,
 ('Abadia de Goiás', 2022, 10): 2,
 ('Abadia de Goiás', 2022, 11): 1,
 ('Abadia de Goiás', 2023, 1): 2,
 ('Abadia de Goiás', 2023, 2): 1,
 ('Abadia de Goiás', 2023, 3): 17,
 ('Abadia de Goiás', 2023, 4): 4,
 ('Abadia de Goiás', 2023, 5): 4,
 ('Abadia de Goiás', 2023, 6): 2,
 ('Abadia de Goiás', 2023, 7): 1,
 ('Abadia de Goiás', 2023, 11): 3,
 ('Abadia de Goiás', 2023, 12): 3,
 ('Abadia de Goiás', 2024, 1): 23,
 ('Abadia de Goiás', 2024, 2): 63,
 ('Abadia de Goiás', 2024, 3): 152,
 ('Abadia de Goiás', 2024, 4): 97,
 ('Abadia de Goiás', 2024, 5): 59,
 ('Abadia de Goiás', 2024, 6): 17,
 ('Abadia de Goiás', 2024, 7): 14,
 ('Abadia de Goiás', 2024, 10): 1,
 ('Abadia de Goiás', 2024, 11): 3,
 ('Abadia de Goiás', 2024, 12): 4,
 ('Abadia de Goiás', 2025, 1): 3,
 ('Abadia de Goiás', 2025, 2): 61,
 ('Abadia de Goiás', 2025, 3): 70,
 ('Abadia de Goiás', 2025, 4): 38,
 ('Abadia de Goiás', 2025, 5): 60,
 ('Abadia de Goiás', 2025, 6): 37,
 ('Abadia de Goiás', 2025, 7): 10,
 ('Abadia de Goiás', 2025, 8): 15,
 ('Abadia de Goiás', 2025, 9): 40,
 ('Abadia de Goiás', 2025, 10): 13,
 ('Abadia de Goiás', 2025, 11): 20,
 ('Abadia de Goiás', 2025, 12): 4,
 ('Abadia dos Dourados', 2007, 4): 1,
 ('Abadia dos Dourados', 2007, 6): 1,
 ('Abadia dos Dourados', 2008, 3): 1,
 ('Abadia dos Dourados', 2008, 4): 1,
 ('Abadia dos Dourados', 2008, 5): 1,
 ('Abadia dos Dourados', 2009, 12): 1,
 ('Abadia dos Dourados', 2010, 4): 3,
 ('Abadia dos Dourados', 2013, 4): 2,
 ('Abadia dos Dourados', 2013, 5): 2,
 ('Abadia dos Dourados', 2013, 6): 2,
 ('Abadia dos Dourados', 2013, 7): 2,
 ('Abadia dos Dourados', 2014, 4): 1,
 ('Abadia dos Dourados', 2014, 7): 1,
 ('Abadia dos Dourados', 2015, 2): 19,
 ('Abadia dos Dourados', 2015, 3): 75,
 ('Abadia dos Dourados', 2015, 4): 17,
 ('Abadia dos Dourados', 2015, 5): 8,
 ('Abadia dos Dourados', 2015, 6): 6,
 ('Abadia dos Dourados', 2016, 2): 2,
 ('Abadia dos Dourados', 2016, 3): 5,
 ('Abadia dos Dourados', 2016, 4): 1,
 ('Abadia dos Dourados', 2017, 1): 1,
 ('Abadia dos Dourados', 2017, 2): 3,
 ('Abadia dos Dourados', 2018, 1): 2,
 ('Abadia dos Dourados', 2018, 2): 3,
 ('Abadia dos Dourados', 2018, 3): 2,
 ('Abadia dos Dourados', 2018, 4): 1,
 ('Abadia dos Dourados', 2018, 10): 1,
 ('Abadia dos Dourados', 2018, 12): 1,
 ('Abadia dos Dourados', 2019, 2): 15,
 ('Abadia dos Dourados', 2019, 3): 6,
 ('Abadia dos Dourados', 2019, 4): 46,
 ('Abadia dos Dourados', 2019, 5): 15,
 ('Abadia dos Dourados', 2019, 6): 5,
 ('Abadia dos Dourados', 2019, 7): 2,
 ('Abadia dos Dourados', 2019, 8): 1,
 ('Abadia dos Dourados', 2019, 9): 3,
 ('Abadia dos Dourados', 2019, 12): 1,
 ('Abadia dos Dourados', 2020, 2): 3,
 ('Abadia dos Dourados', 2020, 3): 10,
 ('Abadia dos Dourados', 2020, 4): 2,
 ('Abadia dos Dourados', 2020, 5): 1,
 ('Abadia dos Dourados', 2020, 6): 1,
 ('Abadia dos Dourados', 2020, 10): 1,
 ('Abadia dos Dourados', 2020, 11): 3,
 ('Abadia dos Dourados', 2021, 1): 2,
 ('Abadia dos Dourados', 2021, 3): 1,
 ('Abadia dos Dourados', 2021, 4): 1,
 ('Abadia dos Dourados', 2021, 11): 1,
 ('Abadia dos Dourados', 2022, 2): 1,
 ('Abadia dos Dourados', 2022, 3): 4,
 ('Abadia dos Dourados', 2022, 4): 14,
 ('Abadia dos Dourados', 2022, 5): 17,
 ('Abadia dos Dourados', 2022, 6): 1,
 ('Abadia dos Dourados', 2022, 12): 7,
 ('Abadia dos Dourados', 2023, 1): 44,
 ('Abadia dos Dourados', 2023, 2): 208,
 ('Abadia dos Dourados', 2023, 3): 246,
 ('Abadia dos Dourados', 2023, 4): 147,
 ('Abadia dos Dourados', 2023, 5): 21,
 ('Abadia dos Dourados', 2023, 6): 2,
 ('Abadia dos Dourados', 2023, 12): 1,
 ('Abadia dos Dourados', 2024, 1): 22,
 ('Abadia dos Dourados', 2024, 2): 34,
 ('Abadia dos Dourados', 2024, 3): 22,
 ('Abadia dos Dourados', 2024, 4): 12,
 ('Abadia dos Dourados', 2024, 5): 2,
 ('Abadia dos Dourados', 2024, 6): 1,
 ('Abadia dos Dourados', 2024, 10): 4,
 ('Abadia dos Dourados', 2024, 11): 15,
 ('Abadia dos Dourados', 2024, 12): 4,
 ('Abadia dos Dourados', 2025, 1): 5,
 ('Abadia dos Dourados', 2025, 2): 11,
 ('Abadia dos Dourados', 2025, 3): 34,
 ('Abadia dos Dourados', 2025, 4): 32,
 ('Abadia dos Dourados', 2025, 5): 25,
 ('Abadia dos Dourados', 2025, 6): 7,
 ('Abadia dos Dourados', 2025, 7): 1,
 ('Abadia dos Dourados', 2025, 11): 1,
 ('Abadia dos Dourados', 2025, 12): 1,
 ('Abadiânia', 2007, 2): 1,
 ('Abadiânia', 2007, 12): 1,
 ('Abadiânia', 2008, 9): 1,
 ('Abadiânia', 2009, 5): 3,
 ('Abadiânia', 2009, 6): 1,
 ('Abadiânia', 2010, 1): 3,
 ('Abadiânia', 2010, 2): 2,
 ('Abadiânia', 2010, 3): 2,
 ('Abadiânia', 2010, 4): 2,
 ('Abadiânia', 2010, 10): 1,
 ('Abadiânia', 2011, 11): 2,
 ('Abadiânia', 2011, 12): 1,
 ('Abadiânia', 2012, 2): 1,
 ('Abadiânia', 2012, 4): 4,
 ('Abadiânia', 2012, 5): 1,
 ('Abadiânia', 2012, 10): 1,
 ('Abadiânia', 2013, 1): 5,
 ('Abadiânia', 2013, 2): 5,
 ('Abadiânia', 2013, 3): 2,
 ('Abadiânia', 2013, 4): 3,
 ('Abadiânia', 2013, 5): 6,
 ('Abadiânia', 2013, 6): 12,
 ('Abadiânia', 2013, 7): 11,
 ('Abadiânia', 2013, 8): 9,
 ('Abadiânia', 2013, 9): 9,
 ('Abadiânia', 2013, 10): 1,
 ('Abadiânia', 2014, 1): 1,
 ('Abadiânia', 2014, 4): 6,
 ('Abadiânia', 2014, 5): 22,
 ('Abadiânia', 2014, 6): 14,
 ('Abadiânia', 2014, 7): 4,
 ('Abadiânia', 2015, 2): 4,
 ('Abadiânia', 2015, 3): 22,
 ('Abadiânia', 2015, 4): 6,
 ('Abadiânia', 2015, 5): 23,
 ('Abadiânia', 2015, 6): 10,
 ('Abadiânia', 2015, 7): 4,
 ('Abadiânia', 2015, 8): 5,
 ('Abadiânia', 2015, 9): 1,
 ('Abadiânia', 2015, 10): 1,
 ('Abadiânia', 2015, 11): 2,
 ('Abadiânia', 2015, 12): 1,
 ('Abadiânia', 2016, 1): 5,
 ('Abadiânia', 2016, 2): 23,
 ('Abadiânia', 2016, 3): 50,
 ('Abadiânia', 2016, 4): 74,
 ('Abadiânia', 2016, 5): 48,
 ('Abadiânia', 2016, 6): 19,
 ('Abadiânia', 2016, 7): 3,
 ('Abadiânia', 2016, 8): 1,
 ('Abadiânia', 2016, 11): 2,
 ('Abadiânia', 2017, 1): 2,
 ('Abadiânia', 2017, 2): 3,
 ('Abadiânia', 2017, 3): 4,
 ('Abadiânia', 2017, 4): 4,
 ('Abadiânia', 2017, 5): 2,
 ('Abadiânia', 2017, 6): 1,
 ('Abadiânia', 2017, 10): 3,
 ('Abadiânia', 2017, 11): 3,
 ('Abadiânia', 2017, 12): 1,
 ('Abadiânia', 2018, 1): 3,
 ('Abadiânia', 2018, 2): 2,
 ('Abadiânia', 2018, 3): 1,
 ('Abadiânia', 2018, 4): 11,
 ('Abadiânia', 2018, 6): 1,
 ('Abadiânia', 2018, 7): 3,
 ('Abadiânia', 2019, 1): 8,
 ('Abadiânia', 2019, 2): 6,
 ('Abadiânia', 2019, 3): 65,
 ('Abadiânia', 2019, 4): 123,
 ('Abadiânia', 2019, 5): 116,
 ('Abadiânia', 2019, 6): 159,
 ('Abadiânia', 2019, 7): 7,
 ('Abadiânia', 2019, 8): 1,
 ('Abadiânia', 2020, 1): 3,
 ('Abadiânia', 2020, 2): 20,
 ('Abadiânia', 2020, 3): 17,
 ('Abadiânia', 2020, 4): 50,
 ('Abadiânia', 2020, 5): 37,
 ('Abadiânia', 2020, 6): 26,
 ('Abadiânia', 2020, 7): 5,
 ('Abadiânia', 2020, 8): 1,
 ('Abadiânia', 2021, 2): 1,
 ('Abadiânia', 2021, 3): 5,
 ('Abadiânia', 2021, 4): 16,
 ('Abadiânia', 2021, 5): 12,
 ('Abadiânia', 2021, 6): 15,
 ('Abadiânia', 2021, 7): 2,
 ('Abadiânia', 2021, 8): 2,
 ('Abadiânia', 2021, 9): 2,
 ('Abadiânia', 2021, 10): 6,
 ('Abadiânia', 2021, 11): 8,
 ('Abadiânia', 2021, 12): 171,
 ('Abadiânia', 2022, 1): 125,
 ('Abadiânia', 2022, 2): 81,
 ('Abadiânia', 2022, 3): 191,
 ('Abadiânia', 2022, 4): 275,
 ('Abadiânia', 2022, 5): 184,
 ('Abadiânia', 2022, 6): 85,
 ('Abadiânia', 2022, 7): 25,
 ('Abadiânia', 2022, 8): 13,
 ('Abadiânia', 2022, 9): 1,
 ('Abadiânia', 2022, 12): 4,
 ('Abadiânia', 2023, 2): 10,
 ('Abadiânia', 2024, 1): 32,
 ('Abadiânia', 2024, 2): 157,
 ('Abadiânia', 2024, 3): 598,
 ('Abadiânia', 2024, 4): 860,
 ('Abadiânia', 2024, 5): 403,
 ('Abadiânia', 2024, 6): 64,
 ('Abadiânia', 2024, 7): 8,
 ('Abadiânia', 2024, 9): 2,
 ('Abadiânia', 2024, 10): 2,
 ('Abadiânia', 2025, 1): 6,
 ('Abadiânia', 2025, 2): 54,
 ('Abadiânia', 2025, 3): 12,
 ('Abaetetuba', 2007, 1): 36,
 ('Abaetetuba', 2007, 2): 41,
 ('Abaetetuba', 2007, 3): 44,
 ('Abaetetuba', 2007, 4): 24,
 ('Abaetetuba', 2007, 5): 11,
 ('Abaetetuba', 2007, 6): 15,
 ('Abaetetuba', 2007, 7): 27,
 ('Abaetetuba', 2007, 8): 4,
 ('Abaetetuba', 2007, 9): 9,
 ('Abaetetuba', 2007, 10): 5,
 ('Abaetetuba', 2007, 11): 4,
 ('Abaetetuba', 2007, 12): 11,
 ('Abaetetuba', 2008, 1): 15,
 ('Abaetetuba', 2008, 2): 15,
 ('Abaetetuba', 2008, 3): 32,
 ('Abaetetuba', 2008, 4): 48,
 ('Abaetetuba', 2008, 5): 11,
 ('Abaetetuba', 2008, 6): 4,
 ('Abaetetuba', 2008, 7): 2,
 ('Abaetetuba', 2008, 8): 2,
 ('Abaetetuba', 2008, 9): 2,
 ('Abaetetuba', 2008, 10): 7,
 ('Abaetetuba', 2008, 11): 6,
 ('Abaetetuba', 2008, 12): 1,
 ('Abaetetuba', 2009, 1): 5,
 ('Abaetetuba', 2009, 2): 5,
 ('Abaetetuba', 2009, 3): 13,
 ('Abaetetuba', 2009, 4): 19,
 ('Abaetetuba', 2009, 5): 2,
 ('Abaetetuba', 2009, 6): 6,
 ('Abaetetuba', 2009, 7): 2,
 ('Abaetetuba', 2009, 8): 7,
 ('Abaetetuba', 2009, 9): 4,
 ('Abaetetuba', 2009, 10): 6,
 ('Abaetetuba', 2009, 11): 7,
 ('Abaetetuba', 2009, 12): 3,
 ('Abaetetuba', 2010, 1): 6,
 ('Abaetetuba', 2010, 2): 10,
 ('Abaetetuba', 2010, 3): 16,
 ('Abaetetuba', 2010, 4): 15,
 ('Abaetetuba', 2010, 5): 33,
 ('Abaetetuba', 2010, 6): 25,
 ('Abaetetuba', 2010, 7): 10,
 ('Abaetetuba', 2010, 8): 108,
 ('Abaetetuba', 2010, 9): 110,
 ('Abaetetuba', 2010, 10): 66,
 ('Abaetetuba', 2010, 11): 68,
 ('Abaetetuba', 2010, 12): 82,
 ('Abaetetuba', 2011, 1): 120,
 ('Abaetetuba', 2011, 2): 98,
 ('Abaetetuba', 2011, 3): 66,
 ('Abaetetuba', 2011, 4): 41,
 ('Abaetetuba', 2011, 5): 13,
 ('Abaetetuba', 2011, 6): 11,
 ('Abaetetuba', 2011, 7): 8,
 ('Abaetetuba', 2011, 8): 10,
 ('Abaetetuba', 2011, 9): 11,
 ('Abaetetuba', 2011, 10): 11,
 ('Abaetetuba', 2011, 11): 27,
 ('Abaetetuba', 2011, 12): 67,
 ('Abaetetuba', 2012, 1): 69,
 ('Abaetetuba', 2012, 2): 95,
 ('Abaetetuba', 2012, 3): 73,
 ('Abaetetuba', 2012, 4): 49,
 ('Abaetetuba', 2012, 5): 19,
 ('Abaetetuba', 2012, 6): 20,
 ('Abaetetuba', 2012, 7): 14,
 ('Abaetetuba', 2012, 8): 39,
 ('Abaetetuba', 2012, 9): 15,
 ('Abaetetuba', 2012, 10): 27,
 ('Abaetetuba', 2012, 11): 14,
 ('Abaetetuba', 2012, 12): 9,
 ('Abaetetuba', 2013, 1): 14,
 ('Abaetetuba', 2013, 2): 14,
 ('Abaetetuba', 2013, 3): 25,
 ('Abaetetuba', 2013, 4): 17,
 ('Abaetetuba', 2013, 5): 9,
 ('Abaetetuba', 2013, 6): 5,
 ('Abaetetuba', 2013, 8): 4,
 ('Abaetetuba', 2013, 9): 6,
 ('Abaetetuba', 2013, 10): 5,
 ('Abaetetuba', 2013, 11): 3,
 ('Abaetetuba', 2014, 1): 10,
 ('Abaetetuba', 2014, 2): 6,
 ('Abaetetuba', 2014, 3): 8,
 ('Abaetetuba', 2014, 4): 8,
 ('Abaetetuba', 2014, 5): 13,
 ('Abaetetuba', 2014, 6): 8,
 ('Abaetetuba', 2014, 7): 3,
 ('Abaetetuba', 2014, 8): 3,
 ('Abaetetuba', 2014, 9): 7,
 ('Abaetetuba', 2014, 10): 4,
 ('Abaetetuba', 2014, 11): 5,
 ('Abaetetuba', 2014, 12): 6,
 ('Abaetetuba', 2015, 1): 8,
 ('Abaetetuba', 2015, 2): 8,
 ('Abaetetuba', 2015, 3): 13,
 ('Abaetetuba', 2015, 4): 3,
 ('Abaetetuba', 2015, 5): 12,
 ('Abaetetuba', 2015, 6): 10,
 ('Abaetetuba', 2015, 7): 13,
 ('Abaetetuba', 2015, 8): 9,
 ('Abaetetuba', 2015, 9): 12,
 ('Abaetetuba', 2015, 10): 22,
 ('Abaetetuba', 2015, 11): 15,
 ('Abaetetuba', 2015, 12): 42,
 ('Abaetetuba', 2016, 1): 51,
 ('Abaetetuba', 2016, 2): 81,
 ('Abaetetuba', 2016, 3): 65,
 ('Abaetetuba', 2016, 4): 45,
 ('Abaetetuba', 2016, 5): 28,
 ('Abaetetuba', 2016, 6): 5,
 ('Abaetetuba', 2016, 7): 15,
 ('Abaetetuba', 2016, 8): 28,
 ('Abaetetuba', 2016, 9): 11,
 ('Abaetetuba', 2016, 10): 22,
 ('Abaetetuba', 2016, 11): 12,
 ('Abaetetuba', 2016, 12): 22,
 ('Abaetetuba', 2017, 1): 34,
 ('Abaetetuba', 2017, 2): 35,
 ('Abaetetuba', 2017, 3): 19,
 ('Abaetetuba', 2017, 4): 20,
 ('Abaetetuba', 2017, 5): 16,
 ('Abaetetuba', 2017, 6): 10,
 ('Abaetetuba', 2017, 7): 13,
 ('Abaetetuba', 2017, 8): 129,
 ('Abaetetuba', 2017, 9): 29,
 ('Abaetetuba', 2017, 10): 13,
 ('Abaetetuba', 2017, 11): 23,
 ('Abaetetuba', 2017, 12): 8,
 ('Abaetetuba', 2018, 1): 30,
 ('Abaetetuba', 2018, 2): 16,
 ('Abaetetuba', 2018, 3): 21,
 ('Abaetetuba', 2018, 4): 18,
 ('Abaetetuba', 2018, 5): 13,
 ('Abaetetuba', 2018, 6): 17,
 ('Abaetetuba', 2018, 7): 6,
 ('Abaetetuba', 2018, 8): 17,
 ('Abaetetuba', 2018, 9): 3,
 ('Abaetetuba', 2018, 10): 14,
 ('Abaetetuba', 2018, 11): 9,
 ('Abaetetuba', 2018, 12): 12,
 ('Abaetetuba', 2019, 1): 13,
 ('Abaetetuba', 2019, 2): 22,
 ('Abaetetuba', 2019, 3): 8,
 ('Abaetetuba', 2019, 4): 12,
 ('Abaetetuba', 2019, 5): 4,
 ('Abaetetuba', 2019, 6): 1,
 ('Abaetetuba', 2019, 7): 2,
 ('Abaetetuba', 2019, 8): 3,
 ('Abaetetuba', 2019, 9): 11,
 ('Abaetetuba', 2019, 10): 6,
 ('Abaetetuba', 2019, 11): 3,
 ('Abaetetuba', 2019, 12): 4,
 ('Abaetetuba', 2020, 1): 16,
 ('Abaetetuba', 2020, 2): 22,
 ('Abaetetuba', 2020, 3): 60,
 ('Abaetetuba', 2020, 4): 21,
 ('Abaetetuba', 2020, 5): 1,
 ('Abaetetuba', 2020, 8): 1,
 ('Abaetetuba', 2020, 9): 1,
 ('Abaetetuba', 2020, 10): 2,
 ('Abaetetuba', 2020, 11): 2,
 ('Abaetetuba', 2020, 12): 4,
 ('Abaetetuba', 2021, 2): 2,
 ('Abaetetuba', 2021, 3): 4,
 ('Abaetetuba', 2021, 4): 4,
 ('Abaetetuba', 2021, 5): 8,
 ('Abaetetuba', 2021, 6): 6,
 ('Abaetetuba', 2021, 7): 1,
 ('Abaetetuba', 2021, 8): 5,
 ('Abaetetuba', 2021, 10): 7,
 ('Abaetetuba', 2021, 12): 6,
 ('Abaetetuba', 2022, 2): 1,
 ('Abaetetuba', 2022, 5): 2,
 ('Abaetetuba', 2022, 7): 1,
 ('Abaetetuba', 2022, 9): 1,
 ('Abaetetuba', 2022, 10): 4,
 ('Abaetetuba', 2023, 1): 1,
 ('Abaetetuba', 2023, 2): 1,
 ('Abaetetuba', 2023, 3): 1,
 ('Abaetetuba', 2023, 4): 1,
 ('Abaetetuba', 2023, 5): 5,
 ('Abaetetuba', 2023, 6): 2,
 ('Abaetetuba', 2023, 7): 1,
 ('Abaetetuba', 2023, 8): 4,
 ('Abaetetuba', 2023, 9): 1,
 ('Abaetetuba', 2023, 10): 5,
 ('Abaetetuba', 2023, 12): 3,
 ('Abaetetuba', 2024, 1): 4,
 ('Abaetetuba', 2024, 2): 32,
 ('Abaetetuba', 2024, 3): 52,
 ('Abaetetuba', 2024, 4): 32,
 ('Abaetetuba', 2024, 5): 12,
 ('Abaetetuba', 2024, 6): 20,
 ('Abaetetuba', 2024, 7): 24,
 ('Abaetetuba', 2024, 8): 32,
 ('Abaetetuba', 2024, 9): 48,
 ('Abaetetuba', 2024, 10): 23,
 ('Abaetetuba', 2024, 11): 15,
 ('Abaetetuba', 2024, 12): 6,
 ('Abaetetuba', 2025, 1): 19,
 ('Abaetetuba', 2025, 2): 30,
 ('Abaetetuba', 2025, 3): 17,
 ('Abaetetuba', 2025, 4): 3,
 ('Abaetetuba', 2025, 5): 4,
 ('Abaetetuba', 2025, 6): 1,
 ('Abaetetuba', 2025, 7): 2,
 ('Abaetetuba', 2025, 8): 9,
 ('Abaetetuba', 2025, 9): 7,
 ('Abaetetuba', 2025, 10): 9,
 ('Abaetetuba', 2025, 11): 2,
 ('Abaetetuba', 2025, 12): 2,
 ('Abaeté', 2007, 1): 8,
 ('Abaeté', 2007, 2): 35,
 ('Abaeté', 2007, 3): 239,
 ('Abaeté', 2007, 4): 177,
 ('Abaeté', 2007, 5): 40,
 ('Abaeté', 2007, 6): 7,
 ('Abaeté', 2007, 7): 1,
 ('Abaeté', 2007, 8): 1,
 ('Abaeté', 2007, 10): 2,
 ('Abaeté', 2008, 2): 37,
 ('Abaeté', 2008, 3): 388,
 ('Abaeté', 2008, 4): 295,
 ('Abaeté', 2008, 5): 15,
 ('Abaeté', 2008, 6): 30,
 ('Abaeté', 2008, 7): 3,
 ('Abaeté', 2008, 12): 2,
 ('Abaeté', 2009, 1): 4,
 ('Abaeté', 2009, 2): 8,
 ('Abaeté', 2009, 3): 6,
 ('Abaeté', 2010, 2): 22,
 ('Abaeté', 2010, 3): 102,
 ('Abaeté', 2010, 4): 141,
 ('Abaeté', 2010, 5): 2,
 ('Abaeté', 2010, 10): 1,
 ('Abaeté', 2010, 11): 2,
 ('Abaeté', 2010, 12): 1,
 ('Abaeté', 2011, 2): 1,
 ('Abaeté', 2011, 3): 6,
 ('Abaeté', 2011, 4): 2,
 ('Abaeté', 2012, 1): 8,
 ('Abaeté', 2012, 2): 1,
 ('Abaeté', 2012, 3): 1,
 ('Abaeté', 2012, 4): 3,
 ('Abaeté', 2012, 5): 2,
 ('Abaeté', 2012, 10): 1,
 ('Abaeté', 2012, 12): 3,
 ('Abaeté', 2013, 1): 8,
 ('Abaeté', 2013, 2): 43,

In [6]:
len(records_per_municipality)

511906

In [ ]:

#* Agrupar por municipio, año y mes, con la clasificacion adecuada
#* se debe realizar un comparativo que permita identificar municipios similares, a partir de condiciones climaticas
#* tambien se debe tener en cuenta el ambiente de la zona, urbno, rural, costero o del interior

In [10]:
# actualizacion de codigos
df['CLASIFICACION'] = df['CLASIFICACION'].replace({1: 10, 2: 11, 3: 12, 4: 12})

# conteo de clasificaciones por año en diccionario
classification_counts = df.groupby(['NU_ANO', 'CLASIFICACION']).size().to_dict()
classification_counts

{(2006, 5.0): 5,
 (2006, 10.0): 3,
 (2007, 5.0): 216507,
 (2007, 8.0): 139770,
 (2007, 10.0): 340276,
 (2007, 11.0): 4104,
 (2007, 12.0): 1912,
 (2008, 0.0): 1,
 (2008, 5.0): 281661,
 (2008, 8.0): 195164,
 (2008, 10.0): 385974,
 (2008, 11.0): 20327,
 (2008, 12.0): 4502,
 (2009, 5.0): 189158,
 (2009, 8.0): 75360,
 (2009, 10.0): 308012,
 (2009, 11.0): 7962,
 (2009, 12.0): 2679,
 (2010, 5.0): 354154,
 (2010, 8.0): 130151,
 (2010, 10.0): 851327,
 (2010, 11.0): 14114,
 (2010, 12.0): 3807,
 (2011, 5.0): 400163,
 (2011, 8.0): 104730,
 (2011, 10.0): 619802,
 (2011, 11.0): 8769,
 (2011, 12.0): 3003,
 (2012, 5.0): 353569,
 (2012, 8.0): 187240,
 (2012, 10.0): 397017,
 (2012, 11.0): 3664,
 (2012, 12.0): 1087,
 (2013, 5.0): 562261,
 (2013, 6.0): 3,
 (2013, 8.0): 271203,
 (2013, 10.0): 1181549,
 (2013, 11.0): 5974,
 (2013, 12.0): 1405,
 (2014, 5.0): 370952,
 (2014, 8.0): 87553,
 (2014, 10.0): 493029,
 (2014, 11.0): 8912,
 (2014, 12.0): 838,
 (2015, 5.0): 696460,
 (2015, 8.0): 309332,
 (2015, 10.0): 1364446,
 (2015, 11.0): 22169,
 (2015, 12.0): 1866,
 (2016, 5.0): 784329,
 (2016, 8.0): 413839,
 (2016, 10.0): 1093496,
 (2016, 11.0): 9772,
 (2016, 12.0): 1060,
 (2017, 5.0): 275451,
 (2017, 8.0): 75202,
 (2017, 10.0): 164451,
 (2017, 11.0): 2864,
 (2017, 12.0): 344,
 (2018, 5.0): 213999,
 (2018, 8.0): 66725,
 (2018, 10.0): 194135,
 (2018, 11.0): 4552,
 (2018, 12.0): 448,
 (2019, 5.0): 709209,
 (2019, 8.0): 239992,
 (2019, 10.0): 1291943,
 (2019, 11.0): 20420,
 (2019, 12.0): 1595,
 (2020, 5.0): 535808,
 (2020, 8.0): 161292,
 (2020, 10.0): 779203,
 (2020, 11.0): 9526,
 (2020, 12.0): 925,
 (2021, 5.0): 478419,
 (2021, 8.0): 83193,
 (2021, 10.0): 442438,
 (2021, 11.0): 4838,
 (2021, 12.0): 440,
 (2022, 5.0): 621,
 (2022, 8.0): 149177,
 (2022, 10.0): 1223671,
 (2022, 11.0): 18660,
 (2022, 12.0): 1541,
 (2023, 8.0): 207752,
 (2023, 10.0): 1276131,
 (2023, 11.0): 20120,
 (2023, 12.0): 1547,
 (2024, 8.0): 542901,
 (2024, 10.0): 5770540,
 (2024, 11.0): 98909,
 (2024, 12.0): 8711,
 (2025, 8.0): 174035,
 (2025, 10.0): 1365515,
 (2025, 11.0): 33491,
 (2025, 12.0): 2575}

In [11]:
df['CLASIFICACION'].value_counts()

CLASIFICACION
10.0    19542958
5.0      6422726
8.0      3614611
11.0      319147
12.0       40285
6.0            3
0.0            1
Name: count, dtype: int64

In [12]:
# filtrar por clasificacion 10, 11 y 12
df = df[df['CLASIFICACION'].isin([10, 11, 12])]
df

,ID_MUNICIP,NOMBRE_MUNICIPIO,SG_UF,NU_ANO,MES,DT_NOTIFIC,DT_SIN_PRI,CS_SEXO,NU_IDADE,CLASIFICACION,EVOLUCION,HOSPITALIZADO,LATITUD,LONGITUD,TempMin,TempMax,Precipitacion
2,310670,Betim,31,2007,3,2007-03-15,2007-03-12,F,4030,10.0,1.0,NaN,-19.96680,-44.2008,17.0,30.0,74.800003
3,310670,Betim,31,2007,3,2007-03-15,2007-03-13,F,4023,10.0,1.0,NaN,-19.96680,-44.2008,17.0,30.0,74.800003
4,310670,Betim,31,2007,3,2007-03-15,2007-03-12,M,4032,10.0,1.0,NaN,-19.96680,-44.2008,17.0,30.0,74.800003
7,292200,Mucuri,29,2007,3,2007-03-12,2007-02-27,M,4011,10.0,1.0,NaN,-18.07540,-39.5565,22.0,32.0,54.700001
13,310670,Betim,31,2007,3,2007-03-13,2007-03-08,F,2000,10.0,1.0,NaN,-19.96680,-44.2008,17.0,30.0,74.800003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30133090,230780,Marco,23,2007,4,2007-04-30,2007-04-26,M,4024,10.0,1.0,NaN,-3.12850,-40.1582,22.0,32.0,285.200012
30133095,220770,Parnaíba,22,2007,5,2007-05-29,2007-05-19,F,4024,10.0,1.0,NaN,-2.90585,-41.7754,24.0,32.0,120.099998
30133096,220770,Parnaíba,22,2007,5,2007-05-29,2007-05-24,F,4023,10.0,1.0,NaN,-2.90585,-41.7754,24.0,32.0,120.099998
30133097,220830,Piracuruca,22,2007,6,2007-06-26,2007-06-24,F,4045,10.0,NaN,NaN,-3.93335,-41.7088,21.0,32.0,36.900002
30133098,220830,Piracuruca,22,2007,6,2007-06-25,2007-06-22,F,4011,10.0,1.0,NaN,-3.93335,-41.7088,21.0,32.0,36.900002

In [17]:
# agrupar por municipio, año y mes y contar el numero de registros por cada grupo
grouped = df.groupby(['NOMBRE_MUNICIPIO', 'NU_ANO', 'MES']).size().reset_index(name='counts')
grouped

       NOMBRE_MUNICIPIO  NU_ANO  MES  counts
0       Abadia de Goiás    2007    4       1
1       Abadia de Goiás    2007    6       3
2       Abadia de Goiás    2008    2       1
3       Abadia de Goiás    2008    3       3
4       Abadia de Goiás    2008    4      14
...                 ...     ...  ...     ...
332360             Óleo    2025    2       1
332361             Óleo    2025    3       2
332362             Óleo    2025    4       2
332363             Óleo    2025    5       1
332364             Óleo    2025    6       2

[332365 rows x 4 columns]